### ISSUE TITLE
Need support for keepalive for connections

### ISSUE THREAD

**Issue by adamb-altiscale** [neillturner/kitchen-ssh#3]
Hopefully this is the right place for this :)

We have an intermittent hang with one of our kitchen-ssh instances. Specifically it happens after the network service is restarted during a converge.

Net::ssh seems to now support keepalive intervals and max retries, and so being able to configure that through kitchen-ssh would be awesome.

**Comment by neillturner** [comment]
In 
there are parameters: 
 :keepalive, :keepalive_interval, :keepalive_maxcount,
https://github.com/net-ssh/net-ssh/blob/master/lib/net/ssh.rb
but these dont seem to be supported in 
Kitchen:SSH

https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/ssh.rb

which is called by SSHBase 
https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/driver/ssh_base.rb

which my plugin calls, so this is really a test kitchen request. 

suggest you log at 
  https://github.com/test-kitchen/test-kitchen/issues

**Comment by adamb-altiscale** [comment]
Filed as https://github.com/test-kitchen/test-kitchen/issues/585, thanks for the prompt response!

**Comment by neillturner** [comment]
you could hack 
   https://github.com/test-kitchen/test-kitchen/blob/master/lib/kitchen/ssh.rb
to add the keep alive parameters pretty easily

**Comment by neillturner** [comment]
closing. this really needs a change to the base code of test-kitchen
