### ISSUE TITLE
no Gemfile on https://rubygems.org/gems/kitchen-ssh

### ISSUE THREAD

**Issue by yeoldegrove** [neillturner/kitchen-ssh#5]
Could you pleae include a Gemfile in the build gem on https://rubygems.org/gems/kitchen-ssh ?

**Comment by neillturner** [comment]
Is there a particular reason why I should include a gem file?

**Comment by yeoldegrove** [comment]
When extracting the gem and trying to use bundler against the sources this will not work without a Gemfile.
Besides the most gems include a Gemfile, even if it's mostly empty ;)

**Comment by neillturner** [comment]
Ok I create one

**Comment by neillturner** [comment]
closed fixed in version 0.0.11
