### ISSUE TITLE
kitchen converge hangs when using kitchen-ssh

### ISSUE THREAD

**Issue by alfianabdi** [neillturner/kitchen-ssh#8]
Hi, I have some problem when using kitchen-ssh.

After run kitchen create which is success, I run kitchen converge. But it just stop in preparing client.rb. 
When I see debug message, it stop in this part : 
[SSH] opening connection to username@host<{:user_known_hosts_file=>"/dev/null", :paranoid=> false, :port=>22 ........................... :keys=>["/path/to/id_rsa"]}>

When I tried using kitchen-ec2, it goes beyond that and preparing chef-client in the new ec2-instance.

I am using 
kitchen-ssh 0.0.12
chefdk 1.1.16
chef-client 12.17.44
kitchen 1.14.2

Could you help me to find out where the problem is and how to solve it?
Thank you.

**Comment by neillturner** [comment]
kitchen-ssh assumes the instance is running. kitchen-ec2 creates the instance so they are different.  So check if you can access the instance via a ssh client like putty on windows or the ssh client on mac.

**Comment by alfianabdi** [comment]
The instance is running. I can even ssh to the machine using "kitchen login" command

**Comment by neillturner** [comment]
i would say it is an ssh issue typically.  if kitchen login works and kitchen-ssh doesn't work then the ssh keys must be different or one is using user and password and another is using ssh key,

**Comment by neillturner** [comment]
if you look at my sample repo ttps://github.com/neillturner/puppet_repo you will see in the 
.kitchen.yml file how i specify my ssh key. 

driver:
  name: ssh_gzip
# set to ssh private key
  ssh_key: spec/test.pem
  username: centos
  sudo: true

if you at https://github.com/test-kitchen/kitchen-ec2
 the ssh key goes in .kitchen.yml file as:
 transport:
 ssh_key: ~/.ssh/your_private_key_file

**Comment by MaRuifeng** [comment]
We encountered almost the same issue. Found out to be because we were running the kitchen commands as a non-root user. That non-root user was not set to be NOPASSWORD in the sudoer file either. So it hang there waiting for input of the password prompted.

**Comment by neillturner** [comment]
closed. added as a tip to readme
